source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

path '..' do
  gem 'repositories'
end

gem 'warden'
gem 'active_model_serializers'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'minitest-rails'
  gem 'pry-rails'
  gem 'mocha'
  gem 'webmock'
end