source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'active_model_serializers'
gem 'ancestry'
gem 'bcrypt'
gem 'carrierwave'
gem 'friendly_id'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'minitest-rails'
  gem 'pry-rails'
end
