source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

path '..' do
  gem 'repositories'
end

gem 'rails_admin'

group :development, :test do
  gem 'pry-rails'
end